### PR TITLE
Parse fallback dirs list to csv

### PR DESCRIPTION
**Pull request by hiromipaw**
Submitting this reg issue #11
Wondering if you'd like also the dirty script that did the parsing... And if the csv columns are ok.

### CODE REVIEW

**Comment by hellais** [comment]
This looks great, thanks for putting it together.

Due to how the auto update of legacy ooniprobe works, we will, however, need this to be part of the `tor-bridges-ip-port.csv` file and not a separate file.

That means splitting the `port` and `orport` lines into separate entries with one stating that it's related to the `dir_port` while the other is related to the `or_port`, similarly to how canonical dir_auths that are already in the file.

Do you think you could integrate this into the `tor-bridges-ip-port.csv` file?

**Comment by teor2345** [comment]
> That means splitting the port and orport lines into separate entries with one stating that it's related to the dir_port while the other is related to the or_port, similarly to how canonical dir_auths that are already in the file.

All supported Tor client versions only use fallback or_ports.
(Clients also use authority or_ports. And relays use authority dir_ports and or_ports.)

So you could ignore fallback dir_ports, and just put their or_ports in the file.

**Comment by hiromipaw** [comment]
Thanks for the feedback.

**Comment by hellais** [comment]
LGTM!

Thanks for putting this together!

**Comment by hellais** [comment]
I also pushed an update to probes. They should start testing these addresses within 6h from now.

**Comment by teor2345** [comment]
Fallback nicknames aren't guaranteed to be unique. I hope that isn't a problem for ooni.

If it is, you should use nickname=fingerprint or something.

**Comment by hellais** [comment]
> Fallback nicknames aren't guaranteed to be unique. I hope that isn't a problem for ooni.

Thanks for the heads up, but that is not an issue for the probes. The only thing they really look at is the IP and port. The nicknames and the fingerprints are mostly used for making sense of the data once it's collected.

**Pull request merged**
